
package proyectotransversal1.vistas;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectotransversal1.accesoDatos.AlumnoData;
import proyectotransversal1.accesoDatos.InscripcionData;
import proyectotransversal1.accesoDatos.MateriaData;
import proyectotransversal1.entidades.Alumno;
import proyectotransversal1.entidades.Inscripcion;
import proyectotransversal1.entidades.Materia;


public class ConsultaAlumnosMateria extends javax.swing.JInternalFrame {
    
    private ArrayList<Materia> listmat; // me muestra las materias
    private ArrayList<Alumno> listalum; // me muestra los alumnos

    private AlumnoData alumData;
    private MateriaData matData;
    private InscripcionData inscData;


    private DefaultTableModel modelo;
    
    
public ConsultaAlumnosMateria() {
        initComponents();
        this.setTitle("Consulta Alumnos por Materia");
        alumData= new AlumnoData(); // inicializo 
        listalum= (ArrayList<Alumno>)alumData.listarAlumnos();
        modelo = new DefaultTableModel();
        matData = new MateriaData();
        listmat = (ArrayList<Materia>) matData.listarMateriasActivas(); 
        armarCabecera();
        cargarMateria();
}
    private void cargarMateria() {
        for (Materia item : listmat) {
            jcbMateria.addItem(item);
        }
}

    private void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("id");
        filaCabecera.add("dni");
        filaCabecera.add("apellido");
        filaCabecera.add("nombre");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
       jTAlumnos.setModel(modelo);
}
     private void borrarFilaTabla() { // esta bien
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) { // hacemos una interaccion y removiendo 
            modelo.removeRow(i);
        }
    }

private void cargarAlumnosPorMateria() {
borrarFilaTabla();
    Materia selectedMateria = (Materia) jcbMateria.getSelectedItem();
    if (selectedMateria != null) {
        ArrayList<Alumno> alumnos = (ArrayList<Alumno>) inscData.obternerAlumnoPorMateria(selectedMateria.getIdMateria());
        for (Alumno alumno : alumnos) {
            modelo.addRow(new Object[]{alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(), alumno.getNombre()});
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlumnos = new javax.swing.JTable();
        jbExit = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 187, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 2, 48)); // NOI18N
        jLabel1.setText("LISTADO DE ALUMNOS POR MATERIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 830, 30));

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione una Materia : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 106, 240, 40));

        jcbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(jcbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 400, 30));

        jTAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTAlumnos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 760, 260));

        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jbExit.setText("SALIR");
        jbExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
       dispose();
        JOptionPane.showMessageDialog(this, "SU CARGA HA SIDO EXITOSA");
    }//GEN-LAST:event_jbExitActionPerformed

    private void jcbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateriaActionPerformed
               cargarAlumnosPorMateria();
    }//GEN-LAST:event_jcbMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAlumnos;
    private javax.swing.JButton jbExit;
    private javax.swing.JComboBox<Materia> jcbMateria;
    // End of variables declaration//GEN-END:variables
}
