/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotransversal1.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author marus
 */
public class General extends javax.swing.JFrame {

    /**
     * Creates new form General
     */
    public General() {
        initComponents();
        this.setTitle("General");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        incribirAlumno = new javax.swing.JMenu();
        jRBIncripcion = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarMateria = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        inscripcion = new javax.swing.JRadioButtonMenuItem();
        notas = new javax.swing.JRadioButtonMenuItem();
        ConsultaAlumnosPorMateria = new javax.swing.JMenu();
        consultaAlumnosPorMateria = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jbExit = new javax.swing.JRadioButtonMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem8.setSelected(true);
        jRadioButtonMenuItem8.setText("jRadioButtonMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));

        escritorio.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        incribirAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        incribirAlumno.setText("ALUMNOS");
        incribirAlumno.setPreferredSize(new java.awt.Dimension(150, 50));

        jRBIncripcion.setSelected(true);
        jRBIncripcion.setText("Inscribir Alumno");
        jRBIncripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIncripcionActionPerformed(evt);
            }
        });
        incribirAlumno.add(jRBIncripcion);

        jMenuBar1.add(incribirAlumno);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu2.setText("MATERIAS");
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        agregarMateria.setSelected(true);
        agregarMateria.setText("Agregar Materia");
        agregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(agregarMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenu3.setText("INSCRIPCION");
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        inscripcion.setSelected(true);
        inscripcion.setText("Incripciones ");
        inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscripcionActionPerformed(evt);
            }
        });
        jMenu3.add(inscripcion);

        notas.setSelected(true);
        notas.setText("Notas");
        notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasActionPerformed(evt);
            }
        });
        jMenu3.add(notas);

        jMenuBar1.add(jMenu3);

        ConsultaAlumnosPorMateria.setText("CONSULTAS");
        ConsultaAlumnosPorMateria.setPreferredSize(new java.awt.Dimension(150, 50));

        consultaAlumnosPorMateria.setSelected(true);
        consultaAlumnosPorMateria.setText("Consulta Alumnos por Materia");
        consultaAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAlumnosPorMateriaActionPerformed(evt);
            }
        });
        ConsultaAlumnosPorMateria.add(consultaAlumnosPorMateria);

        jMenuBar1.add(ConsultaAlumnosPorMateria);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu4.setText("EXIT");
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jbExit.setSelected(true);
        jbExit.setText("Exit");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });
        jMenu4.add(jbExit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBIncripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIncripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnoData ins = new FormularioAlumnoData();
        ins.setVisible(true);
        escritorio.add(ins);
        escritorio.moveToFront(ins);
    }//GEN-LAST:event_jRBIncripcionActionPerformed

    private void agregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMateriaActionPerformed
   
          escritorio.removeAll();
          escritorio.repaint();
          FormularioMateriaData ins = new FormularioMateriaData();
          ins.setVisible(true);
          escritorio.add(ins);
          escritorio.moveToFront(ins);
    }//GEN-LAST:event_agregarMateriaActionPerformed

    private void inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscripcionActionPerformed
           escritorio.removeAll();
           escritorio.repaint();
           FormularioInscripcionData ins = new FormularioInscripcionData();
           ins.setVisible(true);
           escritorio.add(ins);
           escritorio.moveToFront(ins);
    }//GEN-LAST:event_inscripcionActionPerformed

    private void notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Notas ins = new Notas();
        ins.setVisible(true);
        escritorio.add(ins);
        escritorio.moveToFront(ins);
    }//GEN-LAST:event_notasActionPerformed

    private void consultaAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAlumnosPorMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaAlumnosMateria consul = new ConsultaAlumnosMateria();
        consul.setVisible(true);
        escritorio.add(consul);
        escritorio.moveToFront(consul);
    }//GEN-LAST:event_consultaAlumnosPorMateriaActionPerformed

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        JOptionPane.showMessageDialog(this, "SU CARGA HA SIDO EXITOSA");
        Principal salida = new Principal();
        salida.setVisible(true);
    }//GEN-LAST:event_jbExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ConsultaAlumnosPorMateria;
    private javax.swing.JRadioButtonMenuItem agregarMateria;
    private javax.swing.JRadioButtonMenuItem consultaAlumnosPorMateria;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu incribirAlumno;
    private javax.swing.JRadioButtonMenuItem inscripcion;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRBIncripcion;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JRadioButtonMenuItem jbExit;
    private javax.swing.JRadioButtonMenuItem notas;
    // End of variables declaration//GEN-END:variables
}
